package com.pojo;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.uName
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.uGander
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    private String ugander;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.uAge
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    private String uage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.uCareer
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    private String ucareer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.uNote
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    private String unote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.uLog
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    private String ulog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.uPwd
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    private String upwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.uName
     *
     * @return the value of student.uName
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.uName
     *
     * @param uname the value for student.uName
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.uGander
     *
     * @return the value of student.uGander
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public String getUgander() {
        return ugander;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.uGander
     *
     * @param ugander the value for student.uGander
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public void setUgander(String ugander) {
        this.ugander = ugander == null ? null : ugander.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.uAge
     *
     * @return the value of student.uAge
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public String getUage() {
        return uage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.uAge
     *
     * @param uage the value for student.uAge
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public void setUage(String uage) {
        this.uage = uage == null ? null : uage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.uCareer
     *
     * @return the value of student.uCareer
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public String getUcareer() {
        return ucareer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.uCareer
     *
     * @param ucareer the value for student.uCareer
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public void setUcareer(String ucareer) {
        this.ucareer = ucareer == null ? null : ucareer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.uNote
     *
     * @return the value of student.uNote
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public String getUnote() {
        return unote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.uNote
     *
     * @param unote the value for student.uNote
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public void setUnote(String unote) {
        this.unote = unote == null ? null : unote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.uLog
     *
     * @return the value of student.uLog
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public String getUlog() {
        return ulog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.uLog
     *
     * @param ulog the value for student.uLog
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public void setUlog(String ulog) {
        this.ulog = ulog == null ? null : ulog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.uPwd
     *
     * @return the value of student.uPwd
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.uPwd
     *
     * @param upwd the value for student.uPwd
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd == null ? null : upwd.trim();
    }
}