package com.pojo;

import java.util.ArrayList;
import java.util.List;

public class StudentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public StudentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUnameIsNull() {
            addCriterion("uName is null");
            return (Criteria) this;
        }

        public Criteria andUnameIsNotNull() {
            addCriterion("uName is not null");
            return (Criteria) this;
        }

        public Criteria andUnameEqualTo(String value) {
            addCriterion("uName =", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotEqualTo(String value) {
            addCriterion("uName <>", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThan(String value) {
            addCriterion("uName >", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThanOrEqualTo(String value) {
            addCriterion("uName >=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThan(String value) {
            addCriterion("uName <", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThanOrEqualTo(String value) {
            addCriterion("uName <=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLike(String value) {
            addCriterion("uName like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotLike(String value) {
            addCriterion("uName not like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameIn(List<String> values) {
            addCriterion("uName in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotIn(List<String> values) {
            addCriterion("uName not in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameBetween(String value1, String value2) {
            addCriterion("uName between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotBetween(String value1, String value2) {
            addCriterion("uName not between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andUganderIsNull() {
            addCriterion("uGander is null");
            return (Criteria) this;
        }

        public Criteria andUganderIsNotNull() {
            addCriterion("uGander is not null");
            return (Criteria) this;
        }

        public Criteria andUganderEqualTo(String value) {
            addCriterion("uGander =", value, "ugander");
            return (Criteria) this;
        }

        public Criteria andUganderNotEqualTo(String value) {
            addCriterion("uGander <>", value, "ugander");
            return (Criteria) this;
        }

        public Criteria andUganderGreaterThan(String value) {
            addCriterion("uGander >", value, "ugander");
            return (Criteria) this;
        }

        public Criteria andUganderGreaterThanOrEqualTo(String value) {
            addCriterion("uGander >=", value, "ugander");
            return (Criteria) this;
        }

        public Criteria andUganderLessThan(String value) {
            addCriterion("uGander <", value, "ugander");
            return (Criteria) this;
        }

        public Criteria andUganderLessThanOrEqualTo(String value) {
            addCriterion("uGander <=", value, "ugander");
            return (Criteria) this;
        }

        public Criteria andUganderLike(String value) {
            addCriterion("uGander like", value, "ugander");
            return (Criteria) this;
        }

        public Criteria andUganderNotLike(String value) {
            addCriterion("uGander not like", value, "ugander");
            return (Criteria) this;
        }

        public Criteria andUganderIn(List<String> values) {
            addCriterion("uGander in", values, "ugander");
            return (Criteria) this;
        }

        public Criteria andUganderNotIn(List<String> values) {
            addCriterion("uGander not in", values, "ugander");
            return (Criteria) this;
        }

        public Criteria andUganderBetween(String value1, String value2) {
            addCriterion("uGander between", value1, value2, "ugander");
            return (Criteria) this;
        }

        public Criteria andUganderNotBetween(String value1, String value2) {
            addCriterion("uGander not between", value1, value2, "ugander");
            return (Criteria) this;
        }

        public Criteria andUageIsNull() {
            addCriterion("uAge is null");
            return (Criteria) this;
        }

        public Criteria andUageIsNotNull() {
            addCriterion("uAge is not null");
            return (Criteria) this;
        }

        public Criteria andUageEqualTo(String value) {
            addCriterion("uAge =", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageNotEqualTo(String value) {
            addCriterion("uAge <>", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageGreaterThan(String value) {
            addCriterion("uAge >", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageGreaterThanOrEqualTo(String value) {
            addCriterion("uAge >=", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageLessThan(String value) {
            addCriterion("uAge <", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageLessThanOrEqualTo(String value) {
            addCriterion("uAge <=", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageLike(String value) {
            addCriterion("uAge like", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageNotLike(String value) {
            addCriterion("uAge not like", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageIn(List<String> values) {
            addCriterion("uAge in", values, "uage");
            return (Criteria) this;
        }

        public Criteria andUageNotIn(List<String> values) {
            addCriterion("uAge not in", values, "uage");
            return (Criteria) this;
        }

        public Criteria andUageBetween(String value1, String value2) {
            addCriterion("uAge between", value1, value2, "uage");
            return (Criteria) this;
        }

        public Criteria andUageNotBetween(String value1, String value2) {
            addCriterion("uAge not between", value1, value2, "uage");
            return (Criteria) this;
        }

        public Criteria andUcareerIsNull() {
            addCriterion("uCareer is null");
            return (Criteria) this;
        }

        public Criteria andUcareerIsNotNull() {
            addCriterion("uCareer is not null");
            return (Criteria) this;
        }

        public Criteria andUcareerEqualTo(String value) {
            addCriterion("uCareer =", value, "ucareer");
            return (Criteria) this;
        }

        public Criteria andUcareerNotEqualTo(String value) {
            addCriterion("uCareer <>", value, "ucareer");
            return (Criteria) this;
        }

        public Criteria andUcareerGreaterThan(String value) {
            addCriterion("uCareer >", value, "ucareer");
            return (Criteria) this;
        }

        public Criteria andUcareerGreaterThanOrEqualTo(String value) {
            addCriterion("uCareer >=", value, "ucareer");
            return (Criteria) this;
        }

        public Criteria andUcareerLessThan(String value) {
            addCriterion("uCareer <", value, "ucareer");
            return (Criteria) this;
        }

        public Criteria andUcareerLessThanOrEqualTo(String value) {
            addCriterion("uCareer <=", value, "ucareer");
            return (Criteria) this;
        }

        public Criteria andUcareerLike(String value) {
            addCriterion("uCareer like", value, "ucareer");
            return (Criteria) this;
        }

        public Criteria andUcareerNotLike(String value) {
            addCriterion("uCareer not like", value, "ucareer");
            return (Criteria) this;
        }

        public Criteria andUcareerIn(List<String> values) {
            addCriterion("uCareer in", values, "ucareer");
            return (Criteria) this;
        }

        public Criteria andUcareerNotIn(List<String> values) {
            addCriterion("uCareer not in", values, "ucareer");
            return (Criteria) this;
        }

        public Criteria andUcareerBetween(String value1, String value2) {
            addCriterion("uCareer between", value1, value2, "ucareer");
            return (Criteria) this;
        }

        public Criteria andUcareerNotBetween(String value1, String value2) {
            addCriterion("uCareer not between", value1, value2, "ucareer");
            return (Criteria) this;
        }

        public Criteria andUnoteIsNull() {
            addCriterion("uNote is null");
            return (Criteria) this;
        }

        public Criteria andUnoteIsNotNull() {
            addCriterion("uNote is not null");
            return (Criteria) this;
        }

        public Criteria andUnoteEqualTo(String value) {
            addCriterion("uNote =", value, "unote");
            return (Criteria) this;
        }

        public Criteria andUnoteNotEqualTo(String value) {
            addCriterion("uNote <>", value, "unote");
            return (Criteria) this;
        }

        public Criteria andUnoteGreaterThan(String value) {
            addCriterion("uNote >", value, "unote");
            return (Criteria) this;
        }

        public Criteria andUnoteGreaterThanOrEqualTo(String value) {
            addCriterion("uNote >=", value, "unote");
            return (Criteria) this;
        }

        public Criteria andUnoteLessThan(String value) {
            addCriterion("uNote <", value, "unote");
            return (Criteria) this;
        }

        public Criteria andUnoteLessThanOrEqualTo(String value) {
            addCriterion("uNote <=", value, "unote");
            return (Criteria) this;
        }

        public Criteria andUnoteLike(String value) {
            addCriterion("uNote like", value, "unote");
            return (Criteria) this;
        }

        public Criteria andUnoteNotLike(String value) {
            addCriterion("uNote not like", value, "unote");
            return (Criteria) this;
        }

        public Criteria andUnoteIn(List<String> values) {
            addCriterion("uNote in", values, "unote");
            return (Criteria) this;
        }

        public Criteria andUnoteNotIn(List<String> values) {
            addCriterion("uNote not in", values, "unote");
            return (Criteria) this;
        }

        public Criteria andUnoteBetween(String value1, String value2) {
            addCriterion("uNote between", value1, value2, "unote");
            return (Criteria) this;
        }

        public Criteria andUnoteNotBetween(String value1, String value2) {
            addCriterion("uNote not between", value1, value2, "unote");
            return (Criteria) this;
        }

        public Criteria andUlogIsNull() {
            addCriterion("uLog is null");
            return (Criteria) this;
        }

        public Criteria andUlogIsNotNull() {
            addCriterion("uLog is not null");
            return (Criteria) this;
        }

        public Criteria andUlogEqualTo(String value) {
            addCriterion("uLog =", value, "ulog");
            return (Criteria) this;
        }

        public Criteria andUlogNotEqualTo(String value) {
            addCriterion("uLog <>", value, "ulog");
            return (Criteria) this;
        }

        public Criteria andUlogGreaterThan(String value) {
            addCriterion("uLog >", value, "ulog");
            return (Criteria) this;
        }

        public Criteria andUlogGreaterThanOrEqualTo(String value) {
            addCriterion("uLog >=", value, "ulog");
            return (Criteria) this;
        }

        public Criteria andUlogLessThan(String value) {
            addCriterion("uLog <", value, "ulog");
            return (Criteria) this;
        }

        public Criteria andUlogLessThanOrEqualTo(String value) {
            addCriterion("uLog <=", value, "ulog");
            return (Criteria) this;
        }

        public Criteria andUlogLike(String value) {
            addCriterion("uLog like", value, "ulog");
            return (Criteria) this;
        }

        public Criteria andUlogNotLike(String value) {
            addCriterion("uLog not like", value, "ulog");
            return (Criteria) this;
        }

        public Criteria andUlogIn(List<String> values) {
            addCriterion("uLog in", values, "ulog");
            return (Criteria) this;
        }

        public Criteria andUlogNotIn(List<String> values) {
            addCriterion("uLog not in", values, "ulog");
            return (Criteria) this;
        }

        public Criteria andUlogBetween(String value1, String value2) {
            addCriterion("uLog between", value1, value2, "ulog");
            return (Criteria) this;
        }

        public Criteria andUlogNotBetween(String value1, String value2) {
            addCriterion("uLog not between", value1, value2, "ulog");
            return (Criteria) this;
        }

        public Criteria andUpwdIsNull() {
            addCriterion("uPwd is null");
            return (Criteria) this;
        }

        public Criteria andUpwdIsNotNull() {
            addCriterion("uPwd is not null");
            return (Criteria) this;
        }

        public Criteria andUpwdEqualTo(String value) {
            addCriterion("uPwd =", value, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdNotEqualTo(String value) {
            addCriterion("uPwd <>", value, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdGreaterThan(String value) {
            addCriterion("uPwd >", value, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdGreaterThanOrEqualTo(String value) {
            addCriterion("uPwd >=", value, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdLessThan(String value) {
            addCriterion("uPwd <", value, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdLessThanOrEqualTo(String value) {
            addCriterion("uPwd <=", value, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdLike(String value) {
            addCriterion("uPwd like", value, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdNotLike(String value) {
            addCriterion("uPwd not like", value, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdIn(List<String> values) {
            addCriterion("uPwd in", values, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdNotIn(List<String> values) {
            addCriterion("uPwd not in", values, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdBetween(String value1, String value2) {
            addCriterion("uPwd between", value1, value2, "upwd");
            return (Criteria) this;
        }

        public Criteria andUpwdNotBetween(String value1, String value2) {
            addCriterion("uPwd not between", value1, value2, "upwd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 10:07:04 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}